SEL.Presentation/Models/ErrorViewModel.cs
namespace SEL.Presentation.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

SEL.Presentation/ViewModels/DepartmentViewModel.cs
namespace SEL.Presentation.ViewModels
{
    public class DepartmentViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int? ParentDepartmentId { get; set; }
        public List<DepartmentViewModel> ChildDepartments { get; set; }
    }
}

SEL.Presentation/ViewModels/WorkerDepartmentViewModel.cs
namespace SEL.Presentation.ViewModels
{
    public class WorkerDepartmentViewModel
    {
        public WorkerViewModel Worker { get; set; }
        public IEnumerable<DepartmentViewModel> Departments { get; set; }
        public DepartmentViewModel CurrentDepartment { get; set; }
    }
}

SEL.Presentation/ViewModels/WorkerViewModel.cs
namespace SEL.Presentation.ViewModels
{
    public class WorkerViewModel
    {
        public int Id { get; set; }
        public int DepartmentId { get; set; }
        public string FirstName { get; set; }
        public string MidName { get; set; }
        public string LastName { get; set; }
        public int PersonnelNumber { get; set; }
    }
}

SEL.Presentation/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using SEL.BLL.Dtos;
using SEL.BLL.Models;
using SEL.BLL.Services.Interfaces;
using SEL.DAL.Entities;
using SEL.DAL.Repositories;
using SEL.DAL.Repositories.Interfaces;
using SEL.Presentation.ViewModels;

namespace SEL.Presentation.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IDepartmentService _departmentService;
        private readonly IDepartmentHierarchyService _departmentHierarchyService;

        public DepartmentController(IDepartmentService departmentService, 
            IDepartmentHierarchyService departmentHierarchyService)
        {
            _departmentService = departmentService;
            _departmentHierarchyService = departmentHierarchyService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var departments = _departmentService.GetAll().ToList();
            var departmentHierarchyViewModels = _departmentHierarchyService
                .BuildDepartmentHierarchy(departments);
            
            return View(departmentHierarchyViewModels);
        }
        
    }
}

SEL.Presentation/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SEL.Presentation.Models;

namespace SEL.Presentation.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

SEL.Presentation/Controllers/WorkerController.cs
using Microsoft.AspNetCore.Mvc;
using SEL.BLL.Dtos;
using SEL.BLL.Services.Interfaces;
using SEL.DAL.Entities;
using SEL.DAL.Repositories.Interfaces;
using SEL.Presentation.Helpers;
using SEL.Presentation.ViewModels;

namespace SEL.Presentation.Controllers
{
    public class WorkersController : Controller
    {
        private IWorkerService _workerService;
        private IDepartmentService _departmentService;

        public WorkersController(IWorkerService workerService, IDepartmentService departmentService)
        {
            _workerService = workerService;
            _departmentService = departmentService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var workers = _workerService.GetAll();

            List<WorkerViewModel> workerViewModels = workers.Select(worker => new WorkerViewModel
            {
                Id = worker.Id,
                FirstName = worker.FirstName,
                MidName = worker.MidName,
                LastName = worker.LastName,
                PersonnelNumber = worker.PersonnelNumber
            }).ToList();

            return View(workerViewModels);
        }
        
        [HttpPost]
        public IActionResult Delete(int id)
        {
            _workerService.Delete(id);
            
            return RedirectToAction("Index");
        }
        
        [HttpGet]
        public IActionResult Edit(int userId)
        {
            var worker = _workerService.GetById(userId);
            var workerViewModel = Mapper.ConvertToWorkerViewModel(worker);
            
            var departments = _departmentService.GetAll();
            var departmentViewModels = departments
                .Select(d => Mapper.ConvertToDepartmentViewModel(d));
            
            var department = _departmentService.GetById(workerViewModel.DepartmentId);
            var departmentViewModel = Mapper.ConvertToDepartmentViewModel(department);
            
            var viewModel = new WorkerDepartmentViewModel
            {
                Departments = departmentViewModels,
                CurrentDepartment = departmentViewModel,
                Worker = workerViewModel
            };
            
            return View(viewModel);
        }
        
        [HttpPost]
        public IActionResult Edit(WorkerDepartmentViewModel workerDepartmentViewModel)
        {
            var worker = new WorkerDto
            {
                Id = workerDepartmentViewModel.Worker.Id,
                FirstName = workerDepartmentViewModel.Worker.FirstName,
                LastName = workerDepartmentViewModel.Worker.LastName,
                MidName = workerDepartmentViewModel.Worker.MidName,
                DepartmentId = workerDepartmentViewModel.Worker.DepartmentId,
                PersonnelNumber = workerDepartmentViewModel.Worker.PersonnelNumber,
            };
            
            _workerService.Update(worker);
            
            return RedirectToAction("Index");
        }
    }
}

SEL.Presentation/Views/Department/DepartmentHierarchyPartial.cshtml
@model SEL.BLL.Models.DepartmentHierarchy

<ul>
    <li>
        @Model.Name
        @Html.Partial("WorkersCountPartial", Model.Workers.Count)
        @if (Model.Children.Count > 0)
        {
            <ul>
                @foreach (var childDepartment in Model.Children)
                {
                    @Html.Partial("DepartmentHierarchyPartial", childDepartment)
                }
            </ul>
        }
    </li>
</ul>

SEL.Presentation/Views/Department/Index.cshtml
@model List<SEL.BLL.Models.DepartmentHierarchy>

@{
    ViewBag.Title = "Отделы";
    Layout = "_Layout";
}

<h2>Иерархия департаментов</h2>

<div>
    @foreach (var department in Model)
    {
        @Html.Partial("DepartmentHierarchyPartial", department)
    }
</div>

SEL.Presentation/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Домашнаяя страница";
}

<div class="text-center">
    <h1 class="display-4">Тестовое задание</h1>
</div>

SEL.Presentation/Views/Shared/WorkersCountPartial.cshtml
@model int

@if (Model == 1)
{
    <span>(@Model сотрудник)</span> 
}
else if (Model > 1 && Model < 5)
{
    <span>(@Model сотрудникa)</span>
}
else
{
    <span>(@Model сотрудников)</span>
}

SEL.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - SEL.Presentation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/SEL.Presentation.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SEL.Presentation</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Workers" asp-action="Index">Работники</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Department" asp-action="Index">Отделы</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - SEL.Presentation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SEL.Presentation/Views/Workers/Edit.cshtml
@model SEL.Presentation.ViewModels.WorkerDepartmentViewModel

@{
    ViewBag.Title = "Изменить данные работника";
    Layout = "_Layout";
}

<h2>Изменить данные работника</h2>

<form asp-action="Edit" asp-controller="Workers" method="post">
    <div class="form-group">
        <input type="hidden" asp-for="Worker.Id"/>
    </div>
    <div class="form-group">
        <label asp-for="Worker.FirstName" class="control-panel">Имя работника</label>
        <input type="text" asp-for="Worker.FirstName"/>
        <span asp-validation-for="Worker.FirstName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Worker.LastName" class="control-panel">Фамилия работника</label>
        <input type="text" asp-for="Worker.LastName"/>
        <span asp-validation-for="Worker.LastName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Worker.MidName" class="control-panel">Отчество работника</label>
        <input type="text" asp-for="Worker.MidName"/>
        <span asp-validation-for="Worker.MidName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Worker.PersonnelNumber" class="control-panel">Персональный номер сотрудника</label>
        <input type="text" asp-for="Worker.PersonnelNumber"/>
        <span asp-validation-for="Worker.PersonnelNumber" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Worker.DepartmentId" class="control-panel">Отдел сотрудника</label>
        <select asp-for="Worker.DepartmentId" class="form-control">
            @foreach (var department in Model.Departments)
            {
                <option value="@department.Id">@department.Name</option>
            }
        </select>        
        <span asp-validation-for="Worker.DepartmentId" class="text-danger"></span>
    </div>
    
    <button type="submit" class="btn btn-primary">Сохранить</button>
</form>

SEL.Presentation/Views/Workers/Index.cshtml
@model System.Collections.Generic.List<SEL.Presentation.ViewModels.WorkerViewModel>

@{
    ViewBag.Title = "Работники";
    Layout = "_Layout";
}

<h1>Список работников</h1>

<table class="table table-striped">
    <thead class="thead-dark">
    <tr>
        <th>ID</th>
        <th>Имя</th>
        <th>Отчество</th>
        <th>Фамилия</th>
        <th>Табельный номер</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var worker in Model)
    {
        <tr>
            <td>@worker.Id</td>
            <td>@worker.FirstName</td>
            <td>@worker.MidName</td>
            <td>@worker.LastName</td>
            <td>@worker.PersonnelNumber</td>
            <td>
                <div class="d-flex">
                    <a class="btn btn-info btn-sm" asp-action="Edit" asp-route-userId="@worker.Id">Изменить</a>
                    <form asp-action="Delete"  asp-route-Id="@worker.Id"
                          method="post">
                        <button class="btn btn-sm btn-danger" type="submit">
                            Удалить
                        </button>
                    </form>
                </div>
            </td>
        </tr>
    }
    </tbody>
</table>